


GET http://localhost:3000/economy/EcoOne/market/
content-type: application/json

###

GET http://localhost:3000/economy/EcoOne/market/WibbleCity/
content-type: application/json

###

GET http://127.0.0.1:3000/economy/EcoOne/market/WibbleCity/agent/
content-type: application/json

###

GET http://127.0.0.1:3000/economy/EcoOne/market/WibbleCity/agent/8dd7dce5-7089-4661-a068-cef54924ec99/
content-type: application/json


